version: '3'

services:
  web:
    build: build/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www/html/
#      - ./conf/apache:/etc/apache2/sites-enabled/
      - ./conf/nginx:/etc/nginx/sites-available
      - ./shared:/shared
  be:
    build: build/php7.4
    restart: always
    ports:
    - 8000:8000
    volumes:
      - ../:/var/www/html/
      - ./conf/php7.4/cli:/etc/php/7.3/cli/
      - ./conf/php7.4/fpm:/etc/php/7.3/fpm/
      - ./shared:/shared
  fe:
    build: build/php7.4
    restart: always
    volumes:
    - ../:/var/www/html/
    - ./conf/php7.4/cli:/etc/php/7.3/cli/
    - ./conf/php7.4/fpm:/etc/php/7.3/fpm/
    - ./shared:/shared
    command: bash -c "while true; do npm run watch; sleep 60; done"
#  worker:
#    build: build/php7.4
#    volumes:
#    - ../:/var/www/html/
#    - ./conf/php7.4/cli:/etc/php/7.3/cli/
#    - ./conf/php7.4/fpm:/etc/php/7.3/fpm/
#    - ./shared:/shared
#    command: bash -c "cd dashboard && php artisan queue:work --queue=listeners -vvv"
#  scheduler:
#    build: build/php7.4
#    restart: always
#    volumes:
#    - ../:/var/www/html/
#    - ./conf/php7.4/cli:/etc/php/7.3/cli/
#    - ./conf/php7.4/fpm:/etc/php/7.3/fpm/
#    - ./shared:/shared
#    command: bash -c "while true; do php artisan schedule:run -vvv; sleep 60; done"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./shared:/shared
#  cache:
#    image: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./cache:/data
#      - ./shared:/shared
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#  memcached:
#    image: memcached
#    ports:
#      - 11211:11211
#    volumes:
#      - ./shared:/shared
#    environment:
#      - MEMCACHED_USERNAME=root
#      - MEMCACHED_PASSWORD=root_password
#      - MEMCACHED_MEMORY_LIMIT=128
#  elasticsearch:
#    image: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
  adminer:
    image: adminer
    restart: always
    ports:
    - 81:8080
